# Generated by Django 4.2 on 2023-12-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="yookassa_payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
