# Generated by Django 4.2 on 2023-12-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_first_name_alter_users_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='create_event',
            field=models.IntegerField(default=0),
        ),
    ]
