# Generated by Django 4.2 on 2023-12-16 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_emailverifications_expiration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailVerifications',
            new_name='EmailPost',
        ),
    ]
