# Generated by Django 4.2 on 2023-12-15 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='events',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='events',
            name='participants',
            field=models.ManyToManyField(related_name='events_TEAMS', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='events',
            name='tags',
            field=models.ManyToManyField(to='events.tags'),
        ),
        migrations.AddField(
            model_name='events',
            name='winners',
            field=models.ManyToManyField(blank=True, related_name='events_winners', to=settings.AUTH_USER_MODEL),
        ),
    ]
