# Generated by Django 4.2 on 2023-12-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='text_for_email',
            field=models.TextField(blank=True, null=True),
        ),
    ]
